version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: notification-system-postgres
    environment:
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: user_service
      POSTGRES_DB: user_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_service -d user_service"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
