spring:
  application:
    name: user-service
  datasource:
    url: ${DB_URL:jdbc:h2:mem:user_service;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8090/realms/notification-system}
          jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:8090/realms/notification-system/protocol/openid-connect/certs}

server:
  port: ${SERVER_PORT:8081}

nats:
  url: ${NATS_URL:nats://localhost:4222}
